# Generated by Django 3.2.23 on 2023-11-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_followers_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
